using Content.Shared.Preferences;
using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Content.Client.Lobby.UI;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Content.Shared._Funkystation.Records;
using Robust.Client.Graphics;
using Content.Client._Funkystation.Medical.Records.UI;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._CD.Records.UI;

/// <summary>
/// The record editor tab that gets "injected" into the character editor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordEditorGui : Control
{
    /// <summary>
    /// Delegate that tells the editor to save records when the save button is pressed
    /// </summary>
    private readonly Action<PlayerProvidedCharacterRecords> _updateProfileRecords;
    public PlayerProvidedCharacterRecords Records
    {
        get;
        private set;
    } = default!;
    private HumanoidProfileEditor _profileEditor;
    private readonly IPrototypeManager _prototypeManager;
    private readonly ISawmill _sawmill = default!;

    public RecordEditorGui(Action<PlayerProvidedCharacterRecords> updateProfileRecords, HumanoidProfileEditor profileEditor, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _updateProfileRecords = updateProfileRecords;
        _profileEditor = profileEditor;
        _prototypeManager = prototypeManager;

        // from funkystation
        #region Dropdowns

        // add options to each dropdown depending on the enums
        foreach (var insuranceProvider in Enum.GetValues<InsuranceProviders>())
        {
            AddInsuranceProvider(insuranceProvider);
        }

        foreach (var insurancetype in Enum.GetValues<InsuranceTypes>())
        {
            AddInsuranceType(insurancetype);
        }

        foreach (var bloodtype in Enum.GetValues<BloodTypes>())
        {
            AddBloodType(bloodtype);
        }

        #endregion

        #region General

        HeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newHeight))
                return;
            UpdateImperialHeight(newHeight);

            if (!_profileEditor.DoSizeActions)
                return;

            _profileEditor.FindControl<Slider>("HeightSlider").Value = newHeight;
            _profileEditor.SetCharacterHeight(newHeight);
            // UpdateRecords(Records.WithHeight(newHeight));
        };

        WeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newWeight))
                return;
            UpdateImperialWeight(newWeight);

            if (!_profileEditor.DoSizeActions)
                return;

            UpdateRecords(Records.WithWeight(newWeight));
        };

        ContactNameEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithContactName(args.Text));
        };

        #endregion

        #region Employment

        WorkAuthCheckBox.OnToggled += args =>
        {
            UpdateRecords(Records.WithWorkAuth(args.Pressed));
        };

        #endregion

        #region Security

        IdentifyingFeaturesEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithIdentifyingFeatures(args.Text));
        };

        #endregion

        #region Medical

        PostmortemEdit.OnTextChanged += args =>
        {
            UpdateRecords(Records.WithPostmortemInstructions(args.Text));
        };

        #endregion

        #region Entries

        EntryEditorTabs.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-cd-records-employment"));
        EntryEditorTabs.SetTabTitle(1, Loc.GetString("department-Medical"));
        EntryEditorTabs.SetTabTitle(2, Loc.GetString("department-Security"));

        EmploymentEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(Records.WithEmploymentEntries(args.Entries));
        };

        MedicalEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(Records.WithMedicalEntries(args.Entries));
        };

        SecurityEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(Records.WithSecurityEntries(args.Entries));
        };

        #endregion
    }

    public void Update(HumanoidCharacterProfile? profile)
    {
        Records = profile?.CDCharacterRecords ?? PlayerProvidedCharacterRecords.DefaultRecords();
        EmploymentEntrySelector.UpdateContents(Records.EmploymentEntries);
        MedicalEntrySelector.UpdateContents(Records.MedicalEntries);
        SecurityEntrySelector.UpdateContents(Records.SecurityEntries);
        UpdateWidgets();
    }

    public void UpdateRecords(PlayerProvidedCharacterRecords records, bool updateWidgets = true)
    {
        records.EnsureValid();
        Records = records;
        _updateProfileRecords(Records);

        if (updateWidgets)
            UpdateWidgets();
    }

    private void UpdateWidgets()
    {
        if (_profileEditor is not null && _profileEditor.Profile is not null)
        {
            HeightEdit.SetText(_profileEditor.Profile.Height.ToString());
            UpdateImperialHeight(_profileEditor.Profile.Height);
        }
        WeightEdit.SetText(Records.Weight.ToString());
        UpdateImperialWeight(Records.Weight);
        ContactNameEdit.SetText(Records.EmergencyContactName);

        WorkAuthCheckBox.Pressed = Records.HasWorkAuthorization;

        IdentifyingFeaturesEdit.SetText(Records.IdentifyingFeatures);

        PostmortemEdit.SetText(Records.PostmortemInstructions);
    }

    public void UpdateImperialHeight(int newHeight)
    {
        HeightImperialLabel.Text = UnitConversion.GetImperialDisplayLength(newHeight);
    }

    private void UpdateImperialWeight(int newWeight)
    {
        WeightImperialLabel.Text = UnitConversion.GetImperialDisplayMass(newWeight);
    }

    /* insurance dropdowns */
    private void AddInsuranceProvider(InsuranceProviders provider)
    {
        var name = Loc.GetString($"character-records-insurance-provider-{provider.ToString().ToLower()}");
        InsuranceCompanyDropdown.AddItem(name, (int)provider);
    }

    private void AddInsuranceType(InsuranceTypes type)
    {
        var name = Loc.GetString($"character-records-insurance-type-{type.ToString().ToLower()}");
        InsurancePlanDropdown.AddItem(name, (int)type);
    }

    /* blood type dropdown */
    private void AddBloodType(BloodTypes type)
    {
        var name = Loc.GetString($"character-records-blood-{type.ToString().ToLower()}");
        BloodTypeDropdown.AddItem(name, (int)type);
    }

    private void RefreshMedicalInformation()
    {
        MedicalInfoContainer.DisposeAllChildren();

        var info = _prototypeManager.EnumeratePrototypes<MedicalInfoPrototype>()
            .OrderBy(t => Loc.GetString(t.Name))
            .ToList();

        // if there's no prototypes, generate a default label
        if (info.Count < 1)
        {
            MedicalInfoContainer.AddChild(new Label
            {
                Text = Loc.GetString("medical-info-no-info"),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        Dictionary<string, List<string>> infoGroups = new();

        foreach (var entry in info)
        {
            if (entry.Category == null || entry.Category == MedicalInfoCategoryPrototype.Default)
            {
                _sawmill.Warning($"Medical Info prototype {entry.ID} is missing a category (current category: {entry.Category}) and will be skipped.");
                continue;
            }

            var group = infoGroups.GetOrNew(entry.Category);
            group.Add(entry.ID);
        }

        // organize the dictionary after it gens so it stops randomizing the order of the columns
        infoGroups.OrderBy(t => t);

        // setup ui
        foreach (var (categoryId, categoryInfo) in infoGroups)
        {
            if (categoryId == MedicalInfoCategoryPrototype.Default)
                return;

            var category = _prototypeManager.Index<MedicalInfoCategoryPrototype>(categoryId);

            // having to define all of these different containers
            // to get the layout feels wrong but whatever
            var dividerContainer = new PanelContainer
            {
                VerticalExpand = true,
                Margin = new Thickness(5,10),
                SetWidth = 2,
                PanelOverride = new StyleBoxFlat(Color.FromHex("#202028")),
            };

            var container = new ScrollContainer
            {
                HorizontalExpand = true,
                HScrollEnabled = false,
                Margin = new Thickness(10,5),
                SetHeight = 300f,
            };

            var layout = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

            layout.AddChild(new Label
            {
                Text = Loc.GetString(category.Name),
                Margin = new Thickness(5),
                Align = Label.AlignMode.Center,
            });

            container.AddChild(layout);
            MedicalInfoContainer.AddChild(container);

            // don't add the divider if its the last entry
            if (categoryId != infoGroups.Keys.Last())
                MedicalInfoContainer.AddChild(dividerContainer);

            List<RecordChecklistEntry> selectors = new();

            foreach (var infoProto in categoryInfo)
            {
                var trait = _prototypeManager.Index<MedicalInfoPrototype>(infoProto);
                var selector = new RecordChecklistEntry(Loc.GetString(trait.Name));

                selector.Preference = Records.MedicalInfo.Contains(trait.ID) == true;

                selector.PreferenceChanged += preference =>
                {
                    UpdateRecords(preference
                        ? Records.WithMedicalInfo(trait.ID, _prototypeManager)
                        : Records.WithoutMedicalInfo(trait.ID, _prototypeManager),
                        false);
                    UpdateRecords(Records, false);
                };

                selectors.Add(selector);
            }
            foreach (var selector in selectors) { layout.AddChild(selector); }
        }
    }
}
