# This contains random self-contained in this yml Jobs. Some have non unique icons. Some are in departments, but aren't worth sorting out of here.
    
# Rancher (Goonstation)
- type: playTimeTracker
  id: JobRancher

- type: job
  id: Rancher
  name: job-name-rancher
  description: job-description-rancher
  playTimeTracker: JobRancher
  startingGear: RancherGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  - Kitchen
  extendedAccess:
  - Bar
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds
    
- type: startingGear
  id: RancherGear
  equipment:
    id: RancherPDA
    jumpsuit: ClothingUniformJumpsuitJeansBrown
    shoes: ClothingShoesBootsFishing
    ears: ClothingHeadsetService
    
- type: entity
  parent: BasePDA
  id: RancherPDA
  name: rancher PDA
  description: Smells like a farm.
  components:
  - type: Pda
    id: RancherIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-internservice
  - type: PdaBorderColor
    borderColor: "#717059"
    accentVColor: "#00cc35"
  - type: Icon
    state: pda-internservice
    
- type: entity
  parent: IDCardStandard
  id: RancherIDCard
  name: rancher ID card
  components:
  - type: Sprite
    layers:
    - state: default
    - state: idbotanist
  - type: PresetIdCard
    job: Rancher
    

# Waiter (Goonstation)
- type: playTimeTracker
  id: JobWaiter

- type: job
  id: Waiter
  name: job-name-waiter
  description: job-description-waiter
  playTimeTracker: JobWaiter
  startingGear: WaiterGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  - Bar
  extendedAccess:
  - Hydroponics
    
- type: startingGear
  id: WaiterGear
  equipment:
    id: WaiterPDA
    jumpsuit: ClothingUniformJumpsuitSuitRolledSleeves
    shoes: ClothingShoesBootsLaceup
    ears: ClothingHeadsetService
    
- type: entity
  parent: BasePDA
  id: WaiterPDA
  name: waiter PDA
  description: Always on the move. Clearly has a lot of Space Villain Mobile playtime regardless.
  components:
  - type: Pda
    id: WaiterIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-internservice
  - type: PdaBorderColor
    borderColor: "#717059"
    accentVColor: "#00cc35"
  - type: Icon
    state: pda-internservice
    
- type: entity
  parent: IDCardStandard
  id: WaiterIDCard
  name: waiter ID card
  components:
  - type: Sprite
    layers:
    - state: default
    - state: idcook
  - type: PresetIdCard
    job: Waiter
    

# Mechanic (Goonstation)
- type: playTimeTracker
  id: Mechanic

- type: job
  id: Mechanic
  name: job-name-mechanic
  description: job-description-mechanic
  playTimeTracker: JobMechanic
  startingGear: MechanicGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  access:
  - Maintenance
  - Engineering
  - External
    
- type: startingGear
  id: MechanicGear
  equipment:
    id: MechanicPDA
    jumpsuit: ClothingUniformJumpsuitRepairmanNT
    shoes: ClothingShoesBootsSalvage
    ears: ClothingHeadsetEngineering
    
- type: entity
  parent: BasePDA
  id: MechanicPDA
  name: mechanic PDA
  description: Pipe fixer, fix these pipes!
  components:
  - type: Pda
    id: MechanicIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-interntech
  - type: PdaBorderColor
    borderColor: "#717059"
    accentVColor: "#949137"
  - type: Icon
    state: pda-interntech
    
- type: entity
  parent: IDCardStandard
  id: MechanicIDCard
  name: mechanic ID card
  components:
  - type: Sprite
    layers:
    - state: default
    - state: idintern-tech
  - type: PresetIdCard
    job: Mechanic
    
