- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  #- Atlas # worst map voted 2025
  - Bagel
  - Box
  - Cluster
  #- Pillbug
  - Cog # Goobstation - cog is broken
  - Core
  - Elkridge
  - Fland
  - Marathon
  - Meta
  - Oasis
  #- Omega # its broken and i dont know why
  - Origin
  - Saltern
  - Packed
  - Reach # funkystation - operation revive lrp
  - roid_outpost
  - Train
  #- FlandHighPop # 50 players no way we're reaching that
  #- OasisHighPop # 50 players no way we're reaching that
  #- Barratry # Goobstation - Re-add barratry - Funkystation - Barratrauma
  - Kettle
  - Uoui
  #- ResearchOutpost # i give up man